name: Build Release

on:
  push:
    branches: ["main"]
    tags:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  # Single deploy job since we're just deploying
  build:
    if: github.repository_owner == 'myridia'
    runs-on: ubuntu-latest   
    steps:
      - name: install dependencies
        run: |
         sudo apt-get install fuse
         
      - name: Checkout repository
        uses: actions/checkout@v4



      - name: build-release
        run: |
          ./build.sh 
       

      #- name: upload binary windows to release
      #  uses: svenstaro/upload-release-action@v2
      #  with:
      #    repo_token: ${{ secrets.GITHUB_TOKEN }}
      #    file: 'windows/hello_zig_32.exe'
      #    tag: ${{ github.ref }}
      #    overwrite: true
      #    file_glob: true
          
